name: linguabound
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1
  m_widget:
    git:
      url: https://github.com/BlastTea/MWidget.git
      ref: 19376662ee215e49446bc66d8965c86f12e26c41

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
  fonts:
    - family: FeatherBold
      fonts:
        - asset: assets/fonts/FeatherBold/FeatherBold.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"