name: linguabound
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.2+3

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_sticky_header: ^0.6.5
  flutter_svg: ^2.0.10+1
  linguabound_widget:
    git:
      url: https://github.com/BlastTea/linguabound_widget.git
      ref: 7fe9f06876a2e6a66ea0e8a65bded3dd69223b74
  m_widget:
    git:
      url: https://github.com/BlastTea/MWidget.git
      ref: b1191678af1bbefe4ffde909b42804708bb5ab17

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
  fonts:
    - family: FeatherBold
      fonts:
        - asset: packages/linguabound_widget/fonts/FeatherBold/FeatherBold.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "assets/images/logo-background.png"
  adaptive_icon_foreground: "assets/images/logo-foreground.png"
